#!/bin/bash
#$ -cwd
#$ -o /dev/null
#$ -e /dev/null
# Set the number of processes here:
#$ -pe smp 4
# Set the number of processors (if different from the above) here:
setenv OMP_NUM_THREADS $NSLOTS
# Change the name of the execuatable here:
./hello > output.txt
